Version: v1
Config:
  StepCount: 2000
  StepSize: 0.01
  Separator: ":"
Box:
- Id: cons0
  Type: sin
  Input:
  - Id: period
    Source: "param0"
  - Id: shift
    Source: "param1"
- Id: pers0
  Type: integrate
  Input:
  - Id: x
    Source: "cons0:x"
Variable:
- Id: "param0"
  Type: float
  Value: 10
- Id: "param1"
  Type: float
  Value: 2
- Id: "cons0:x"
  Type: float
  Value: 0.0
- Id: "pers0:sx"
  Type: float
  Value: 0.0